### ISSUE TITLE
ModuleNotFoundError: No module named 'qmaterialwidgets'

### ISSUE THREAD

**Issue by joseph16388** [271374667/NuitkaGUI#13]
from qmaterialwidgets import (BodyLabel, DisplayLabel, IconWidget, OutlinedPushButton,
ModuleNotFoundError: No module named 'qmaterialwidgets'

源代码里缺这个模块

**Comment by 271374667** [comment]
原作者是pyqt-fluent-widget的作者，你可以去Github上找他，或者看看有没有人frok了他的仓库
