### ISSUE TITLE
基础参数

### ISSUE THREAD

**Issue by CheshireCC** [271374667/NuitkaGUI#5]
参数中考虑加入 
```
--follow-import-to
```

该参数的值为模块、包、或用户指定目录。
当自定义模块、代码文件比较多时我们通常会将这些需要编译的代码放进同一目录下，然后使用这个参数指定将自定义模块或自己编写的全部代码文件进行编译。

**Comment by 271374667** [comment]
其实其他的功能还在测试中，现在的框架过段时间还要重构，新功能可能得延后一到两个版本



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月29日(星期四) 凌晨1:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [271374667/NuitkaGUI] 基础参数 (Issue #5)





 
参数中考虑加入
 --follow-import-to  
该参数的值为模块、包、或用户指定目录。
 当自定义模块、代码文件比较多时我们通常会将这些需要编译的代码放进同一目录下，然后使用这个参数指定将自定义模块或自己编写的全部代码文件进行编译。

**Comment by CheshireCC** [comment]
> 其实其他的功能还在测试中，现在的框架过段时间还要重构，新功能可能得延后一到两个版本
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月29日(星期四) 凌晨1:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [271374667/NuitkaGUI] 基础参数 (Issue #5) 参数中考虑加入 --follow-import-to 该参数的值为模块、包、或用户指定目录。 当自定义模块、代码文件比较多时我们通常会将这些需要编译的代码放进同一目录下，然后使用这个参数指定将自定义模块或自己编写的全部代码文件进行编译。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

软件支持 mingw 编译器，可以考虑把 Clang 参数也加上[/doge]

**Comment by 271374667** [comment]
mingw和clang和嵌入文件都已经在新版本中加上了
