### ISSUE TITLE
plugin-list

### ISSUE THREAD

**Issue by CheshireCC** [271374667/NuitkaGUI#6]
plugins :

```
python -m niutka --plugin-list
```

all plugins here
```
"""
                 The following plugins are available in Nuitka
--------------------------------------------------------------------------------
 anti-bloat        Patch stupid imports out of widely used library modules source codes.
 data-files        Include data files specified by package configuration files.
 delvewheel        Required for 'support' of delvewheel using packages in standalone mode.
 dill-compat       Required for 'dill' package compatibility.
 dll-files         Include DLLs as per package configuration files.
 enum-compat       Required for Python2 and 'enum' package.
 eventlet          Support for including 'eventlet' dependencies and its need for 'dns' package monkey patching.
 gevent            Required by the 'gevent' package.
 gi                Support for GI package typelib dependency.
 glfw              Required for OpenGL and 'glfw' package in standalone mode.
 implicit-imports  Provide implicit imports of package as per package configuration files.
 kivy              Required by 'kivy' package.
 matplotlib        Required for 'matplotlib' module.
 multiprocessing   Required by Python's 'multiprocessing' module.
 no-qt             Disable all Qt bindings for standalone mode.
 options-nanny     Inform the user about potential problems as per package configuration files.
 pbr-compat        Required by the 'pbr' package in standalone mode.
 pkg-resources     Workarounds for 'pkg_resources'.
 pmw-freezer       Required by the 'Pmw' package.
 pylint-warnings   Support PyLint / PyDev linting source markers.
 pyqt5             Required by the PyQt5 package.
 pyqt6             Required by the PyQt6 package for standalone mode.
 pyside2           Required by the PySide2 package.
 pyside6           Required by the PySide6 package for standalone mode.
 pywebview         Required by the 'webview' package (pywebview on PyPI).
 tk-inter          Required by Python's Tk modules.
 transformers      Provide implicit imports for transformers package.
 trio              Required for 'trio' package.
 upx               Compress created binaries with UPX automatically.
"""
```

and , we just support a part of them now?

**Comment by 271374667** [comment]
i dont really know what happen when enable some plugins like gi, glwf,It is untest.My bad,soon be Ok.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "271374667/NuitkaGUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 中午12:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[271374667/NuitkaGUI] plugin-list (Issue #6)





 
plugins :
 python -m niutka --plugin-list  
all plugins here
 """                  The following plugins are available in Nuitka --------------------------------------------------------------------------------  anti-bloat        Patch stupid imports out of widely used library modules source codes.  data-files        Include data files specified by package configuration files.  delvewheel        Required for 'support' of delvewheel using packages in standalone mode.  dill-compat       Required for 'dill' package compatibility.  dll-files         Include DLLs as per package configuration files.  enum-compat       Required for Python2 and 'enum' package.  eventlet          Support for including 'eventlet' dependencies and its need for 'dns' package monkey patching.  gevent            Required by the 'gevent' package.  gi                Support for GI package typelib dependency.  glfw              Required for OpenGL and 'glfw' package in standalone mode.  implicit-imports  Provide implicit imports of package as per package configuration files.  kivy              Required by 'kivy' package.  matplotlib        Required for 'matplotlib' module.  multiprocessing   Required by Python's 'multiprocessing' module.  no-qt             Disable all Qt bindings for standalone mode.  options-nanny     Inform the user about potential problems as per package configuration files.  pbr-compat        Required by the 'pbr' package in standalone mode.  pkg-resources     Workarounds for 'pkg_resources'.  pmw-freezer       Required by the 'Pmw' package.  pylint-warnings   Support PyLint / PyDev linting source markers.  pyqt5             Required by the PyQt5 package.  pyqt6             Required by the PyQt6 package for standalone mode.  pyside2           Required by the PySide2 package.  pyside6           Required by the PySide6 package for standalone mode.  pywebview         Required by the 'webview' package (pywebview on PyPI).  tk-inter          Required by Python's Tk modules.  transformers      Provide implicit imports for transformers package.  trio              Required for 'trio' package.  upx               Compress created binaries with UPX automatically. """  
and , we just support a part of them now?

**Comment by 271374667** [comment]
Now when the program runs, it will retrieve all the available plugins from the command line for the current version. However, this method does not meet my expectations. I hope these things can be completed automatically, or hide the plugins that Nuitka actually opens by default. This feature will be further improved in the future
